<?php

return [
    //都道府県選択画面用
    'detail' => [
        'hokkaido' => ['北海道地区'],
        'tohoku' => ['東北地区','青森、岩手、宮城、秋田、山形、福島'],
        'kanto' => ['関東地区','茨城、栃木、群馬、埼玉、千葉、東京、神奈川'],
        'chubu' => ['中部地区','新潟、富山、石川、福井、山梨、長野、岐阜、静岡、愛知、三重'],
        'kinki' => ['近畿地区','滋賀、京都、大阪、兵庫、奈良、和歌山'],
        'chugoku' => ['中国地区','鳥取、島根、岡山、広島、山口'],
        'shikoku' => ['四国地区','徳島、香川、愛媛、高知'],
        'kyushu' => ['九州地区','福岡、佐賀、長崎、熊本、大分、宮崎、鹿児島、沖縄'],
    ],

    'prefectures_en' => [
        '北海道' => 'hokkaido',
        '青森県' => 'aomori',
        '岩手県' => 'iwate',
        '宮城県' => 'miyagi',
        '秋田県' => 'akita',
        '山形県' => 'yamagata',
        '福島県' => 'fukushima',
        '茨城県' => 'ibaraki',
        '栃木県' => 'tochigi',
        '群馬県' => 'gunma',
        '埼玉県' => 'saitama',
        '千葉県' => 'chiba',
        '東京都' => 'tokyo',
        '神奈川県' => 'kanagawa',
        '新潟県' => 'niigata',
        '富山県' => 'toyama',
        '石川県' => 'ishikawa',
        '福井県' => 'fukui',
        '山梨県' => 'yamanashi',
        '長野県' => 'nagano',
        '岐阜県' => 'gifu',
        '静岡県' => 'shizuoka',
        '愛知県' => 'aichi',
        '三重県' => 'mie',
        '滋賀県' => 'shiga',
        '京都府' => 'kyoto',
        '大阪府' => 'osaka',
        '兵庫県' => 'hyogo',
        '奈良県' => 'nara',
        '和歌山県' => 'wakayama',
        '鳥取県' => 'tottori',
        '島根県' => 'shimane',
        '岡山県' => 'okayama',
        '広島県' => 'hiroshima',
        '山口県' => 'yamaguchi',
        '徳島県' => 'tokushima',
        '香川県' => 'kagawa',
        '愛媛県' => 'ehime',
        '高知県' => 'kochi',
        '福岡県' => 'fukuoka',
        '佐賀県' => 'saga',
        '長崎県' => 'nagasaki',
        '熊本県' => 'kumamoto',
        '大分県' => 'oita',
        '宮崎県' => 'miyazaki',
        '鹿児島県' => 'kagoshima',
        '沖縄県' => 'okinawa',
    ],

    'region_kanji' => function (string $prefecture_en) {
        return match ($prefecture_en) {
            'hokkaido' => '北海道',
            'aomori', 'iwate', 'miyagi', 'akita', 'yamagata', 'fukushima' => '東北地方',
            'ibaraki', 'tochigi', 'gunma', 'saitama', 'chiba', 'tokyo', 'kanagawa' => '関東地方',
            'niigata', 'toyama', 'ishikawa', 'fukui', 'yamanashi', 'nagano', 'gifu', 'shizuoka', 'aichi', 'mie' => '中部地方',
            'shiga', 'kyoto', 'osaka', 'hyogo', 'nara', 'wakayama' => '近畿地方',
            'tottori', 'shimane', 'okayama', 'hiroshima', 'yamaguchi' => '中国地方',
            'tokushima', 'kagawa', 'ehime', 'kochi' => '四国地方',
            'fukuoka', 'saga', 'nagasaki', 'kumamoto', 'oita', 'miyazaki', 'kagoshima', 'okinawa' => '九州地方',
            'hirei' => '比例代表制',
            default => null,
        };
    },
];
