<?php

return [
    'detail' => [
        'hokkaido' => ['北海道地区'],
        'tohoku' => ['東北地区','青森、岩手、宮城、秋田、山形、福島'],
        'kanto' => ['関東地区','茨城、栃木、群馬、埼玉、千葉、東京、神奈川'],
        'chubu' => ['中部地区','新潟、富山、石川、福井、山梨、長野、岐阜、静岡、愛知、三重'],
        'kinki' => ['近畿地区','滋賀、京都、大阪、兵庫、奈良、和歌山'],
        'chugoku' => ['中国地区','鳥取、島根、岡山、広島、山口'],
        'shikoku' => ['四国地区','徳島、香川、愛媛、高知'],
        'kyushu' => ['九州地区','福岡、佐賀、長崎、熊本、大分、宮崎、鹿児島、沖縄'],
    ],

    'prefectures_en' => [
        '北海道' => 'hokkaido',
        '青森' => 'aomori',
        '岩手' => 'iwate',
        '宮城' => 'miyagi',
        '秋田' => 'akita',
        '山形' => 'yamagata',
        '福島' => 'fukushima',
        '茨城' => 'ibaraki',
        '栃木' => 'tochigi',
        '群馬' => 'gunma',
        '埼玉' => 'saitama',
        '千葉' => 'chiba',
        '東京' => 'tokyo',
        '神奈川' => 'kanagawa',
        '新潟' => 'niigata',
        '富山' => 'toyama',
        '石川' => 'ishikawa',
        '福井' => 'fukui',
        '山梨' => 'yamanashi',
        '長野' => 'nagano',
        '岐阜' => 'gifu',
        '静岡' => 'shizuoka',
        '愛知' => 'aichi',
        '三重' => 'mie',
        '滋賀' => 'shiga',
        '京都' => 'kyoto',
        '大阪' => 'osaka',
        '兵庫' => 'hyogo',
        '奈良' => 'nara',
        '和歌山' => 'wakayama',
        '鳥取' => 'tottori',
        '島根' => 'shimane',
        '岡山' => 'okayama',
        '広島' => 'hiroshima',
        '山口' => 'yamaguchi',
        '徳島' => 'tokushima',
        '香川' => 'kagawa',
        '愛媛' => 'ehime',
        '高知' => 'kochi',
        '福岡' => 'fukuoka',
        '佐賀' => 'saga',
        '長崎' => 'nagasaki',
        '熊本' => 'kumamoto',
        '大分' => 'oita',
        '宮崎' => 'miyazaki',
        '鹿児島' => 'kagoshima',
        '沖縄' => 'okinawa',
    ]
];
